### PR TITLE
Update 07-CI.Rmd

### PR DESCRIPTION
**Pull request by halseylg**

### CODE REVIEW

**Comment by Lakens** [comment]
Thanks - this is amazingly helpful, and great edits. Really, really appreciarted.

**Comment by Lakens** [comment]
I am just leaving that spelling error in that comment. I am sorry I make so many :)

**Comment by halseylg** [comment]
I grateful to be able to read your book online, anytime - very useful indeed. Glad to be able to give a tiny something back. Will read more in due course - looking forward to it.

By the way, are you conducive to giving a 40-min seminar on stats? I'm starting to think about seminar speakers for my Faculty for next academic year.

Cheers, Lewis

**Comment by Lakens** [comment]
Happy to give something back, I regularly give seminars - send me an email!

**Pull request merged**
