### PR TITLE
Update 01-pvalue.Rmd

### PR DESCRIPTION
**Pull request by halseylg**

### CODE REVIEW

**Comment by Lakens** [comment]
Thanks - sorry for slow response, was travelling. About the background color - I will change this in all code that users can see and copy to run themselves - but not in the figures I generate for the book. The background color is set in one place, and for the web version it is slightly oof white (for ease on eyes) but when compling to latex it will be white - so it needs to remain a variable set in one place.

**Comment by Lakens** [comment]
And good catch I am not simuolating onesample t-tests. Code must have changed, but I did not update the text. Will do it now.

**Comment by Lakens** [comment]
About the question: FOR THE ABOVE CODE, IS THERE A PACKAGE USED? (FOR calc_d_dist AND FOR add_type1_error). - no, the functions are defined once at the beginning of the RMarkdown doc, because they are used several times.

**Comment by halseylg** [comment]
Hi Daniel,

Good point. I didn't always spot when the code was for the reader and when for the figures, as I was often reading from the editable version and have been keen to try out much of your coding.

Thanks, Lewis

**Pull request merged**
