### PR TITLE
Fixed various typos and inconsistencies in Ch. 1

### PR DESCRIPTION
**Pull request by elenlefoll**
My edits also include stylistic suggestions to make some passages easier to understand. Also see the additional file comments_Elen.txt with the more important content-related comments and suggestions.

### CODE REVIEW

**Review by Lakens — COMMENTED** [review]
Thanks for the edits - I have to check some of the lay-out suggestions (the extra asterisks and the / before <) after rendering, as they look fine now and I don't know what will happen. I appreciate the effort, but next, time, feel free to reach out before going through the chapter. There are now so many changes, and git makes it so difficult to see which changes someone has made, I basically have to blindly accept all your suggestions, without knowing which changes you have made to my textbook. It is appreciated, but also a very dangerous way to make changes to a textbook. This is more a frustration with how git works than with the effort you put in, but I wish I could see what is being changed. I see whole paragraphs flagged, someone within which something has changed - which is often a comma at then end, but sometimes more.

**Comment by elenlefoll** [comment]
Yes, I am sorry about this. It seemed like the best way to make mostly very minor suggested changes as I was reading the chapter, but git flags up far more changes than I actually made. For instance, I did not add any forward slashes or asterisks. I think that RStudio did that automatically when I opened and saved in the .qmd file... So I hope that this does not cause you any issues. In future, I will only flag up anything major as a GitHub issue. It seems a shame to not be able to contribute more but clearly git is not appropriate for editing. I do apologise as I did not know this before. Thanks for your understanding and for the great resource!

**Comment by Lakens** [comment]
Hi, in general, anything easy for me to do is better raised as an issue (e.g. Check for double spaces, remove double indent in quote x). If you want to make the changes, it is appreciated, but then make many small pull requests, not one with everything. Thanks!

**Comment by Lakens** [comment]
To answer the remaining 2 questions:

"It might be useful to think of the answer to the question whether an effect is absent after observing p > 0.05 as 無 (mu)"
--> Mu is printed as an Asian character.

> Yes, because it is an Asian word that is not really translatable. 

"**Q5:** Why can’t you conclude that the null hypothesis is true, when you observe a statistically non-significant *p*-value (*p* \> alpha)?"
--> I was surprised to see that the "correct" answer is the one about possibly making a Type 2 error. This sounds to me like a Type 1 error.
When P > alpha we do not have a significant result. So we can only make a Type 2 error.

**Pull request merged**
