### PR TITLE
Update 12-bias.Rmd

### PR DESCRIPTION
**Pull request by halseylg**

### CODE REVIEW

**Comment by Lakens** [comment]
Hi ,thanks again. I will change back some suggestions (it is 'z-curve' as a name for the technique, so 'z-curves does not exist). I will look into the truncnorm package - it works on my computer, but maybe it no longer works for the last R version? That would be a shame.

**Comment by Lakens** [comment]
Truncnorm still works and install for me. I will keep it for now - which error did you get?

**Comment by halseylg** [comment]
Hi Daniel,

This morning I got a response from CRAN - our university had lost it's link to the relevant 'mirror' over the last few days, and this probably explains why I couldn't get access to Truncnorm. Interestingly, it also wasn't coming up as an available package to download.

This has now changed, however. So it looks like it's me rather than the package. Good news and sorry for the hassle.

Cheers, Lewis

**Comment by Lakens** [comment]
OK, no problem, better safe than sorry.

**Pull request merged**
